---
version: "2"
services:
  zookeeper:
    networks: ["kafka-network"]
    container_name: zookeeper.kafka-network
    hostname: zookeeper
    image: confluentinc/cp-zookeeper:latest
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  kafka:
    networks: ["kafka-network"]
    container_name: kafka.kafka-network
    hostname: kafka0
    image: confluentinc/cp-kafka:latest
    labels:
      - "custom.project=kafkajs-zstd"
      - "custom.service=kafka"
    ports:
      - 9091:9091
      - 9092:9092
      - 9093:9093
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181

      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: DOCKER_COMPOSE:PLAINTEXT, DOCKER:PLAINTEXT, LOCAL:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: DOCKER_COMPOSE://kafka0:9091, DOCKER://host.docker.internal:9093, LOCAL://localhost:9092
      KAFKA_INTER_BROKER_LISTENER_NAME: DOCKER_COMPOSE

      KAFKA_SASL_ENABLED_MECHANISMS: PLAIN
      KAFKA_SASL_MECHANISM_INTER_BROKER_PROTOCOL: PLAIN
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_LOG4J_ROOT_LOGLEVEL: INFO
      KAFKA_LOG4J_LOGGERS: "kafka.controller=INFO,kafka.producer.async.DefaultEventHandler=INFO,state.change.logger=INFO"
      CONFLUENT_SUPPORT_METRICS_ENABLE: "false"
    depends_on:
      - zookeeper

  kafka-ui:
    networks: ["kafka-network"]
    container_name: kafka-ui.kafka-network
    hostname: kafka-ui.kafka-network
    image: provectuslabs/kafka-ui
    ports:
      - 8080:8080
    environment:
      - KAFKA_CLUSTERS_0_NAME=local
      - KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS=kafka0:9091
    depends_on:
      - kafka

networks:
  kafka-network:
    name: kafka-network
