// Code generated by xgen. DO NOT EDIT.

package schema

// PurchaseOrder ...
type PurchaseOrder *PurchaseOrderType

// PurchaseOrderType ...
type PurchaseOrderType struct {
	OrderDateAttr string       `xml:"OrderDate,attr,omitempty"`
	ShipTo        []*USAddress `xml:"ShipTo"`
	BillTo        *USAddress   `xml:"BillTo"`
}

// USAddress ...
type USAddress struct {
	CountryAttr string `xml:"country,attr,omitempty"`
	Name        string `xml:"name"`
	Street      string `xml:"street"`
	City        string `xml:"city"`
	State       string `xml:"state"`
	Zip         int    `xml:"zip"`
}
